version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - kong-network

  kong:
    image: kong/kong-gateway:3.8.1.0
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000 
    depends_on:
      - kong-database
    ports:
      - 8000:8000  # Proxy
      - 8001:8001  # Admin API
    networks:
      - kong-network

  konga:
    image: pantsel/konga
    container_name: konga
    environment:
      NODE_ENV: production
    ports:
      - 1337:1337  # Konga dashboard
    depends_on:
      - kong
    networks:
      - kong-network

volumes:
  kong-db-data: # Persistent volume for Postgres
    driver: local

networks:
  kong-network:
    driver: bridge