name: Kong Deploy

on:
  push:
    paths:
      - 'kong/**'
    branches:
      - main

env:
  image_name: kong
  container_name: kong

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH And Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          echo "Private key entered"
          ssh -v -i ~/.ssh/private_key.pem root@172.19.73.133
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem root@172.19.73.133 <<EOF
          mkdir -p Project
          cd Project || exit
          git pull origin main
          git log --oneline -10
          docker compose up -d --build
          EOF

          rm -f ~/.ssh/private_key.pem
