name: Kong Deploy

on:
  push:
    paths:
      - 'kong/**'
    branches:
      - main

env:
  image_name: kong
  container_name: kong
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH And Deploy
        env: 
         PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "Private key Entered"
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@172.19.73.133<<EOF
          
          mkdir Project
          cd Project
          git checkout main
          git pull
          git log --oneline -10
          docker compose up -d --build
          EOF

          rm -f private_key.pem

      permissions:
        contents: read
        actions: write
        id-token: write