name: Node1 Service

on:
  push:
    paths:
      - 'node1/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: nodejs-service-1
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: docker image build and push - CI
      #   uses : docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./node1/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}:${{github.run_number}}

      # - name: Test connectivity
      #   run: ping 172.19.64.1

      # - name: SSH to instance and run container - CD
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: 172.19.73.133
      #     username: root
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     debug: true
      #     script: |
      #       whoami
      #       ls -al
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH to Windows machine and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir Project